#pragma once
#define SMALL_SCREEN_WIDTH 80
#define SMALL_SCREEN_HEIGHT 27
#define LARGE_SCREEN_WIDTH 120
#define LARGE_SCREEN_HEIGHT 40
#define TETRIS_FIELD_WIDTH 12
#define TETRIS_FIELD_HEIGHT 18
#define SNAKE_FIELD_WIDTH 18
#define SNAKE_FIELD_HEIGHT 18
#define FIRST_PERSON_SCREEN_WIDTH 120
#define FIRST_PERSON_SCREEN_HEIGHT 40